[2025-07-31T03:54:25.027+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataproc_gcs_to_bq.submit_pyspark_job manual__2025-07-31T03:49:53.206748+00:00 [queued]>
[2025-07-31T03:54:25.063+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataproc_gcs_to_bq.submit_pyspark_job manual__2025-07-31T03:49:53.206748+00:00 [queued]>
[2025-07-31T03:54:25.068+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-07-31T03:54:25.110+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): submit_pyspark_job> on 2025-07-31 03:49:53.206748+00:00
[2025-07-31T03:54:25.124+0000] {standard_task_runner.py:60} INFO - Started process 1959 to run task
[2025-07-31T03:54:25.130+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dataproc_gcs_to_bq', 'submit_pyspark_job', 'manual__2025-07-31T03:49:53.206748+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dataproc_gcs_to_bq.py', '--cfg-path', '/tmp/tmp_3qe8w7s']
[2025-07-31T03:54:25.135+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask submit_pyspark_job
[2025-07-31T03:54:25.292+0000] {task_command.py:423} INFO - Running <TaskInstance: dataproc_gcs_to_bq.submit_pyspark_job manual__2025-07-31T03:49:53.206748+00:00 [running]> on host e63302d63f25
[2025-07-31T03:54:25.494+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dataproc_gcs_to_bq' AIRFLOW_CTX_TASK_ID='submit_pyspark_job' AIRFLOW_CTX_EXECUTION_DATE='2025-07-31T03:49:53.206748+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-31T03:49:53.206748+00:00'
[2025-07-31T03:54:25.496+0000] {dataproc.py:2208} INFO - Submitting job
[2025-07-31T03:54:25.517+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2025-07-31T03:54:25.524+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-07-31T03:54:26.035+0000] {dataproc.py:2220} INFO - Job 3e2f189a-c59c-436e-a132-4302f6f5db78 submitted successfully.
[2025-07-31T03:54:26.096+0000] {dataproc.py:2254} INFO - Waiting for job 3e2f189a-c59c-436e-a132-4302f6f5db78 to complete
[2025-07-31T03:55:39.340+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2255, in execute
    self.hook.wait_for_job(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 477, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 724, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "target-de"
  job_id: "3e2f189a-c59c-436e-a132-4302f6f5db78"
}
placement {
  cluster_name: "gcs-to-bq-cluster"
  cluster_uuid: "2dca9e39-4cf3-4bff-bb10-3d9d10986262"
}
pyspark_job {
  main_python_file_uri: "gs://sp500-***-de-project/sp500-dataproc/gcs_to_bq_dataproc.py"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78?project=target-de&region=us-east1\ngcloud dataproc jobs wait \'3e2f189a-c59c-436e-a132-4302f6f5db78\' --region \'us-east1\' --project \'target-de\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/\ngs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/driveroutput.*"
  state_start_time {
    seconds: 1753934130
    nanos: 76214000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1753934067
    nanos: 133380000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1753934067
    nanos: 169974000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1753934067
    nanos: 624220000
  }
}
yarn_applications {
  name: "GCS to BigQuery"
  state: FINISHED
  progress: 1
  tracking_url: "http://gcs-to-bq-cluster-m.us-east1-b.c.target-de.internal.:8088/proxy/application_1753933958410_0001/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/"
job_uuid: "3e2f189a-c59c-436e-a132-4302f6f5db78"
done: true

[2025-07-31T03:55:39.348+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dataproc_gcs_to_bq, task_id=submit_pyspark_job, execution_date=20250731T034953, start_date=20250731T035425, end_date=20250731T035539
[2025-07-31T03:55:39.366+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 32 for task submit_pyspark_job (Job failed:
reference {
  project_id: "target-de"
  job_id: "3e2f189a-c59c-436e-a132-4302f6f5db78"
}
placement {
  cluster_name: "gcs-to-bq-cluster"
  cluster_uuid: "2dca9e39-4cf3-4bff-bb10-3d9d10986262"
}
pyspark_job {
  main_python_file_uri: "gs://sp500-***-de-project/sp500-dataproc/gcs_to_bq_dataproc.py"
}
status {
  state: ERROR
  details: "Google Cloud Dataproc Agent reports job failure. If logs are available, they can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78?project=target-de&region=us-east1\ngcloud dataproc jobs wait \'3e2f189a-c59c-436e-a132-4302f6f5db78\' --region \'us-east1\' --project \'target-de\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/\ngs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/driveroutput.*"
  state_start_time {
    seconds: 1753934130
    nanos: 76214000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1753934067
    nanos: 133380000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1753934067
    nanos: 169974000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1753934067
    nanos: 624220000
  }
}
yarn_applications {
  name: "GCS to BigQuery"
  state: FINISHED
  progress: 1
  tracking_url: "http://gcs-to-bq-cluster-m.us-east1-b.c.target-de.internal.:8088/proxy/application_1753933958410_0001/"
}
driver_output_resource_uri: "gs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-us-east1-267262649432-l3tjozhi/google-cloud-dataproc-metainfo/2dca9e39-4cf3-4bff-bb10-3d9d10986262/jobs/3e2f189a-c59c-436e-a132-4302f6f5db78/"
job_uuid: "3e2f189a-c59c-436e-a132-4302f6f5db78"
done: true
; 1959)
[2025-07-31T03:55:39.416+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-07-31T03:55:39.438+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
